kind: Source
apiVersion: v1
name: my-source
spec:
  kind: EventHub
  identity:
    kind: MicrosoftEntraWorkloadID
    clientId: b6a2b7f2-427a-4cbd-8aa8-9e9aa2c13a8f
  properties:
    host: drasitestluke.servicebus.windows.net
    eventHubs:
      - eventhub1
    bootstrapWindow: 5
