apiVersion: v1
kind: ContinuousQuery
name: luke-actions-monitor
spec:
  sources:
    subscriptions:
      - id: my-source
  mode: query
  query: |
    MATCH (e:Event)
    RETURN e.time, e.category, e.operationName, e.callerIpAddress