apiVersion: v1
kind: ContinuousQuery
name: eventhub-test-query
spec:
  sources:
    subscriptions:
      - id: my-source
  mode: query
  query: |
    MATCH (e:Event)
    WHERE e.category = 'Administrative'
    RETURN e.time AS time,
           e.category AS category,
           e.operationName AS operation,
           e.resultType AS result,
           e.callerIpAddress AS sourceIp,
           e.identity.claims.name AS userName