apiVersion: v1
kind: ContinuousQuery
name: luke-actions-monitor
spec:
  sources:
    subscriptions:
      - id: my-source
  mode: query
  query: >
    MATCH (n)
    WHERE n.sequenceNumber > 1661
    RETURN n

