kind: Source
apiVersion: v1
name: azure-role-eventhub-source
spec:
  kind: EventHub
  properties:
    connectionString: Endpoint=sb://drasitestluke.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XMAw8v6fwq3i0IwqEVbJsuHZSnb6lh0wC+AEhId9Ny4=
    eventHubs:
      - eventhub1
    bootstrapWindow: 5
