kind: Source
apiVersion: v1
name: my-source
spec:
  kind: EventHub
  properties:
    connectionString: Endpoint=sb://drasitestluke.servicebus.windows.net/;SharedAccessKeyName=test;SharedAccessKey=n5cZrSTt/+IBGN+Wx+QkrXrxw0DPcP+ry+AEhET6who=;EntityPath=eventhub1
    eventHubs:
      - eventhub1
    bootstrapWindow: 5
