kind: Source
apiVersion: v1
name: azure-role-eventhub-source
spec:
  kind: EventHub
  identity:
    kind: MicrosoftEntraWorkloadID
    clientId: 50421fa8-277f-4c22-a085-d5880422dc52
  properties:
    host: azrole.servicebus.windows.net
    eventHubs:
      - drasieventhub1
    bootstrapWindow: 5
