---
kind: ContinuousQuery
apiVersion: v1
name: azure-role-change-vmadminlogin
spec:
  mode: query
  sources:
    subscriptions:
      - id: azure-role-eventhub-source
        nodes:
          - sourceLabel: eventhub1
        pipeline:
          - extract-role-assignments
          - extract-authorization-data
    middleware:
      - name: extract-role-assignments
        kind: unwind
        eventhub1:
          - selector: $.records[*]
            label: RoleAssignment
            key: $.correlationId
      - name: extract-authorization-data
        kind: unwind
        RoleAssignment:
          - selector: $.properties
            label: RoleProperties
            key: $.requestbody
  query: |
    MATCH (r:RoleAssignment)--(p:RoleProperties)
    WHERE r.operationName = 'MICROSOFT.AUTHORIZATION/ROLEASSIGNMENTS/WRITE'
    AND r.resultType = 'Success'
    AND p.requestbody CONTAINS '1c0163c0-47e6-4577-8991-ea5c82e286e4'
    RETURN
      r.correlationId AS correlationId,
      r.time AS timestamp,
      r.resourceId AS resourceId,
      r.operationName AS operationName,
      r.resultType AS resultType,
      r.RoleLocation AS roleLocation,
      r.callerIpAddress AS callerIpAddress,
      r.tenantId AS tenantId,
      p.requestbody AS requestBody,
      r.identity AS identity
