---
kind: ContinuousQuery
apiVersion: v1
name: azure-role-change-vmadminlogin
spec:
  mode: query
  sources:
    subscriptions:
      - id: azure-role-eventhub-source
        nodes:
          - sourceLabel: eventhub1
        pipeline:
          - extract-role-assignments
    middleware:
      - name: extract-role-assignments
        kind: unwind
        eventhub1:
          - selector: $.records[?(@.operationName == 'MICROSOFT.AUTHORIZATION/ROLEASSIGNMENTS/WRITE' || @.operationName == 'MICROSOFT.AUTHORIZATION/ROLEASSIGNMENTS/DELETE')]
            label: RoleAssignment
            key: $.time
            properties:
              time: $.time
              resourceId: $.resourceId
              operationName: $.operationName
              operationType: $.resultType
              category: $.category
              level: $.level
              correlationId: $.correlationId
              caller: $.identity.claims.name
              callerIpAddress: $.callerIpAddress
              tenantId: $.tenantId
              subscriptionId: $.identity.authorization.scope
              status: $.resultSignature
              subStatus: $.resultType
              durationMs: $.durationMs
              properties: $.properties
              entity: $.properties.entity
              requestBody: $.properties.requestbody
              resourceType: "Microsoft.Authorization/roleAssignments"
              resourceProviderName: "Microsoft.Authorization"

  query: |
    MATCH (r:RoleAssignment)
    RETURN r.correlationId AS correlationId,
           r.time AS timestamp,
           r.resourceId AS resourceId,
           r.operationName AS operationName,
           r.operationType AS operationType,
           r.category AS category,
           r.level AS level,
           r.callerIpAddress AS callerIpAddress,
           r.caller AS caller,
           r.tenantId AS tenantId,
           r.subscriptionId AS subscriptionId,
           r.status AS status,
           r.subStatus AS subStatus,
           r.durationMs AS durationMs,
           r.properties AS properties,
           r.entity AS entity,
           r.resourceType AS resourceType,
           r.resourceProviderName AS resourceProviderName,
           r.requestBody AS requestBody