kind: ContinuousQuery
apiVersion: v1
name: azure-role-assignments
spec:
  mode: query
  sources:    
    subscriptions:
      - id: azure-role-eventhub-source
        nodes:
          - sourceLabel: eventhub1
        pipeline:
          - extract-role-assignments
  middleware:
    - id: extract-role-assignments
      name: extract-role-assignments
      kind: unwind
      RoleAssignment:
        - selector: $.records[*]
          label: Role
          key: $.correlationId
          properties:
            callerIpAddress: $.callerIpAddress
            resourceId: $.resourceId
            operationName: $.operationName
            email: $.identity.claims['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress']
            principalName: $.identity.claims['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name']
            tenantId: $.identity.claims['http://schemas.microsoft.com/identity/claims/tenantid']
            # Extract from responseBody if available, fallback to null if not present
            principalId: $.properties.responseBody.properties.principalId
            principalType: $.properties.responseBody.properties.principalType
            roleDefinitionId: $.properties.responseBody.properties.roleDefinitionId
            scope: $.properties.responseBody.properties.scope
            # For delete/start events, these may not be present, so fallback to null
            callerName: $.identity.claims['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name']
            callerEmail: $.identity.claims['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress']
            resultType: $.resultType
            resultSignature: $.resultSignature
            timestamp: $.time
            location: $.RoleLocation
  query: >
    MATCH
      (r:RoleAssignment)
    RETURN
      r.correlationId as correlationId,
      r.resourceId as resourceId,
      r.principalId as principalId,
      r.principalType as principalType,
      r.roleDefinitionId as roleDefinitionId,
      r.scope as scope,
      r.resultType as resultType,
      r.resultSignature as resultSignature,
      r.callerIpAddress as callerIpAddress,
      r.callerName as callerName,
      r.callerEmail as callerEmail,
      r.email as email,
      r.principalName as principalName,
      r.tenantId as tenantId,
      r.timestamp as timestamp,
      r.location as location