---
kind: ContinuousQuery
apiVersion: v1
name: azure-role-change-vmadminlogin
spec:
  mode: query
  sources:
    subscriptions:
      - id: azure-role-eventhub-source
        nodes:
          - sourceLabel: eventhub1
        pipeline:
          - extract-role-assignments
    middleware:
      - name: extract-role-assignments
        kind: unwind
        eventhub1:
          - selector: $.records[*]
            label: RoleAssignment
            key: $.correlationId
  query: |
    MATCH (r:RoleAssignment)
    RETURN
      r.correlationId AS correlationId,
      r.RoleLocation AS roleLocation,
      r.time AS timestamp,
      r.resourceId AS resourceId,
      r.operationName AS operationName,
      r.category AS category,
      r.resultType AS resultType,
      r.resultSignature AS resultSignature,
      r.durationMs AS durationMs,
      r.callerIpAddress AS callerIpAddress,
      r.level AS level,
      r.tenantId AS tenantId,
      r.identity AS identity,
      r.properties AS properties
