---
kind: ContinuousQuery
apiVersion: v1
name: azure-role-change-vmadminlogin
spec:
  mode: query
  sources:
    subscriptions:
      - id: azure-role-eventhub-source
        nodes:
          - sourceLabel: eventhub1
        pipeline:
          - extract-role-assignments
    middleware:
      - name: extract-role-assignments
        kind: unwind
        eventhub1:
          - selector: $.records[*]
            label: RoleAssignment
            key: $.correlationId
  query: |
    MATCH (r:RoleAssignment)
    WHERE r.operationName = "MICROSOFT.AUTHORIZATION/ROLEASSIGNMENTS/WRITE"
      AND r.resultType = "Success"
      AND r.properties.requestbody CONTAINS
        "1c0163c0-47e6-4577-8991-ea5c82e286e4"
    RETURN
      r.correlationId AS correlationId,
      r.time AS timestamp,
      r.resourceId AS resourceId,
      r.tenantId AS tenantId,
      r.RoleLocation AS roleLocation,
      r.callerIpAddress AS callerIpAddress,
      r.identity AS identity,
      r.properties AS properties
