# This line specifies the base image for the Docker container.
# "FROM" is a Docker instruction used to set the base image from which the container is built.
# "mcr.microsoft.com/devcontainers/universal:latest" is the image being used.
# It is a universal image provided by Microsoft, hosted on the Microsoft Container Registry (MCR),
# designed for development containers. The "latest" tag specifies the most recent version of this image.
FROM mcr.microsoft.com/devcontainers/universal:latest

# Update packages and install dependencies before Drasi CLI
RUN apt-get update && \
    apt-get install -y libc6 && \
    curl -fsSL https://raw.githubusercontent.com/drasi-project/drasi-platform/main/cli/installers/install-drasi-cli.sh | bash \
    && echo "Drasi CLI installed successfully" \
    || echo "Failed to install Drasi CLI"
